GET http://localhost:8080/books

###

GET http://localhost:8080/books/5

###

POST http://localhost:8080/books
Content-Type: application/json

{
"isbn": "test123123",
"title": "tytul1",
"author": "autor1",
"publisher": "publisher1",
"type": "type1"
}

###

DELETE http://localhost:8080/books/4

###

PUT http://localhost:8080/books/2
Content-Type: application/json

{
  "isbn": "test123123",
  "title": "tytul1",
  "author": "autor1",
  "publisher": "publisher1",
  "type": "type1"
}

###
